### ISSUE TITLE
Document build dependencies

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#118]
The following build dependencies (for Ubuntu) should be added to the documentation:
rocm-dev
cmake
libpci-dev

**Comment by jedwards-AMD** [comment]
This should have increase priority now that the repo is live. I am getting questions regarding missing header files.

**Comment by jedwards-AMD** [comment]
The doxygen package is required as well.

**Comment by mlucinhdl** [comment]
Fix merged in #208
