### ISSUE TITLE
GM logging is enabled by default

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#195]
It appears that gm logging is enabled by default, and has a log rate hard coded below 1 second. I used a configuration file with the following entry, and my informational messages for metric values were output at a rate of about 10 per second:
.
actions:
- name: start
  module: gm
  device: 33367
  monitor: true
  metrics:
    temp: true 50 0
  sample_interval: 10000
  terminate: false
.
Notice that the above configuration file doesn't enable metric logging because the log_interval value is not specified. When I do specify it, like this:
actions:
- name: start
  module: gm
  device: 33367
  monitor: true
  metrics:
    temp: true 50 0
  sample_interval: 10000
  log_interval: 5000
  terminate: false
.
The output for monitored metrics still occurs at a rate much higher than I would expect.
There is a similar problem with the sample interval metric. Violations are triggered correctly, but when violations occur they are reported at a higher rate than I would expect. The violation messages occur once per second when I specify a 10 second sampling interval.

**Comment by mlucinhdl** [comment]
Please retest.
