### ISSUE TITLE
atomic_opt registers are indicating NOT SUPPORTED for all devices

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#196]
The PEQT module queries the PCIe link and determines whether or not the system has the capabilities to support atomic operations. I expected some link and slot values to not be supported, but the following values should provide support and information regarding the capabilities:
.
[INFO  ] [623212.284224] pcie_act_1 peqt atomic_op_128_CAS_completer NOT SUPPORTED
[INFO  ] [623212.284233] pcie_act_1 peqt atomic_op_32_completer NOT SUPPORTED
[INFO  ] [623212.284242] pcie_act_1 peqt atomic_op_64_completer NOT SUPPORTED
[INFO  ] [623212.284251] pcie_act_1 peqt atomic_op_routing NOT SUPPORTED

**Comment by mlucinhdl** [comment]
This has been clarified so I'm closing it.
