### ISSUE TITLE
run './rvs -t', get RVS-CLI: could not load .so error.

### ISSUE THREAD

**Issue by chaojunliu2015** [ROCm-Developer-Tools/ROCmValidationSuite#205]
root@gfxval-OG:/opt/rocm/rvs# ./rvs -t

ROCm Validation Suite (version 0.0.15)

Modules available:
RVS-CLI: could not load .so '/opt/rocm/rvs//libgm.so.0' reason: librocm_smi64.so: cannot open shared object file: No such file or directory
RVS-CLI: module 'gm' not available.
RVS-CLI: could not open module: gm
        gpup:
                Description: ROCm Validation Suite GPUP module
                config: module (string), version (string), installed (bool),user (string), groups (collection of strings), file (string), owner (s                                                     tring), group (string), permission (int), type (int), exists (bool)
                output: pass (bool)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
warning: removing bogus exact problem (does not meet assertion requirements for solution)
        gst:
                Description: ROCm Validation Suite GST module
                config: target_stress (float), copy_matrix (bool), ramp_interval (int), tolerance (float), max_violations (int), log_interval (int                                                     )
                output: pass (bool)
RVS-CLI: could not load .so '/opt/rocm/rvs//libiet.so.0' reason: librocm_smi64.so: cannot open shared object file: No such file or directory
RVS-CLI: module 'iet' not available.
RVS-CLI: could not open module: iet
        pebb:
                Description: ROCm Validation Suite PEBB module
                config: host_to_device (bool), device_to_host (bool), log_interval (integer)
                output: interval_bandwidth (float array), bandwidth (float array)

**Comment by mlucinhdl** [comment]
Hi Chao, 
1. I just updated build instructions with a list of prerequisites.
Please check that you have all that you need installed on your system.

2. It seems that you didn't build rocm_smi_lib. Please follow README instruction on steps to perform before building rvs.

Hope this helps.

**Comment by chaojunliu2015** [comment]
I did 1. install the pre-request packages. 2. I did build rocm_smi_lib before building rvs.
Still has the same issue. I think the problem happens here:

root@gfxval-OG:~/lucy_tools/build# sudo bin/rvs -d 3
[RESULT] [  1531.99695 ] action_1 gpup 18984 mem_banks_count 1
[RESULT] [  1531.99737 ] action_1 gpup 18984 0 version_major 0
[RESULT] [  1531.99836 ] action_2 gpup 18984 mem_banks_count 1
[RESULT] [  1531.105177] action_3 peqt FALSE

**Comment by chaojunliu2015** [comment]
librocm_smi64.so is under this dir, but the tool complains 'No such file'.
/root/lucy_tools/build/rocm_smi_lib/librocm_smi64.so

**Comment by mlucinhdl** [comment]
Can you please go to your .../build/bin folder and execute command:

`ldd libgm.so.0.0.16`

and send me output.

**Comment by mlucinhdl** [comment]
It seems you are in build folder.
You should run it from build/bin folder...

**Comment by chaojunliu2015** [comment]
root@gfxval-OG:~/lucy_tools/build/bin# ldd libgm.so.0.0.15
        linux-vdso.so.1 =>  (0x00007ffd36ae8000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa4e44cd000)
        libpci.so.3 => /lib/x86_64-linux-gnu/libpci.so.3 (0x00007fa4e42c0000)
        librocm_smi64.so => /root/lucy_tools/ROCmValidationSuite/../build/rocm_smi_lib/librocm_smi64.so (0x00007fa4e4091000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa4e3d0f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa4e3a06000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa4e37f0000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa4e3426000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa4e4961000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fa4e320c000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fa4e2ff1000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fa4e4b54000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fa4e2de9000)

**Comment by chaojunliu2015** [comment]
root@gfxval-OG:/opt/rocm/rvs# ./rvs
[RESULT] [  2045.76749 ] action_1 gpup 18984 mem_banks_count 1
[RESULT] [  2045.76890 ] action_1 gpup 18984 0 version_major 0
[RESULT] [  2045.77297 ] action_2 gpup 18984 mem_banks_count 1
[RESULT] [  2045.84955 ] action_3 peqt FALSE
RVS-CLI: could not load .so '/opt/rocm/rvs//libgm.so.0' reason: librocm_smi64.so: cannot open shared object file: No such file or directory
RVS-CLI: module 'gm' not available.
RVS-CLI: action 'action_4' could not crate action object in module 'gm'

**Comment by mlucinhdl** [comment]
Yes, RVS has to be run from bin folder.
