### ISSUE TITLE
The GM modules terminate flag should terminate the process

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#224]
The GM module has a terminate flag that drives the following functionality (as specified in the SRS): 

"If the terminate key is true the GM monitor will terminate the RVS **process** when a bounds violation is   encountered on any of the metrics"

Currently, if terminate=true, the monitoring is terminated and the RVS process will continue running any tests were configured. The purpose of the terminate flag is to ensure dangerous bounds violations result in a cessation of testing, not monitoring. Simply terminating the entire process would be acceptable.

**Comment by mlucinhdl** [comment]
Implementation merged in #251
