### ISSUE TITLE
Wrong Command in prerequisite link

### ISSUE THREAD

**Issue by sreekant1441** [ROCm-Developer-Tools/ROCmValidationSuite#227]
Just an FYI that in the web page of prerequisites [https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/blob/master/PREREQUISITES.md] the command to install is wrongly entered as
sudo apt-install <package> instead of apt-get install.

Please do the correction as required.

**Comment by mlucinhdl** [comment]
Fix merged in #233
