### ISSUE TITLE
rocBLAS installation got 'not supported on this GPU' errors

### ISSUE THREAD

**Issue by chaojunliu2015** [ROCm-Developer-Tools/ROCmValidationSuite#248]
When run these commands,
cd rocBLAS
./install.sh -d

Got the following errors,
# Writing Kernels...
# Launching kernel compilation processes (cpus=1 kernelsPerCpu=523)
[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 100% (0.0 secs elapsed)
# Waiting for kernel compilation processes...
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1272:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1283:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1294:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1465:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1485:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1505:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1717:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1728:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1739:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1910:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1930:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.s:1950:1: error: instruction not supported on this GPU
v_add_co_u32 v19, vcc, v18, s44                    // rowPtr <- inc for non-0 (tt1+vc1))
^
clang-7: error: no such file or directory: 'Cijk_Ailk_Bljk_SB_MT128x016x16_AF0EM01_ASEM01_BL1_GRVW02_GSU32_ISA803_K1_KLA_LPB00_MGWVW01_NLCA01_NLCB01_PGR1_PLR1_TT08_02_VAW01_VW02_WG16_08_02_WGM01.o'
clang-7: error: no input files
Tensile::FATAL: Assembler process returned with code 1

**Comment by mlucinhdl** [comment]
Hi, it seems you do not have compatible video card in your system or you are not member of sudo and video groups. Anyhow, this issue should be posted on rocBLAS  issue list so I am closing it.

**Comment by chaojunliu2015** [comment]
After do more experiment, I found need to do './install.sh -dc', otherwise will get the above error. It's better to update document to add '-c' option.
cd rocBLAS
./install.sh -dc

**Comment by mlucinhdl** [comment]
HI, we do not recommend adding "-c" because:
a) it compiles things that are not needed for the actual rocBlas library nor for the RVS (rocBlas clients are out of the RVS scope)
b) it requires some more libraries (e.g.: boost which is usually big)
c) on the server project -cd fails because it cannot find the libboost

As is already indicated in README.md, if dependencies are already installed you may run without "-d"
If the problem persists, please contact rocBLAS team.
