### ISSUE TITLE
Error during make package

### ISSUE THREAD

**Issue by chaojunliu2015** [ROCm-Developer-Tools/ROCmValidationSuite#253]
root@gfxval-OG:~/lucy_tools/build# make package
[  1%] Generating RVS man.1 files
[  1%] Built target man1
[  1%] Generating RVS Programmer's Reference Guide
[  1%] Built target doc
[  2%] Generating RVS User Guide
[  2%] Built target userguide
[ 17%] Built target rvs
[ 25%] Built target gpup
[ 33%] Built target pesm
[ 38%] Built target rcqt
[ 45%] Built target peqt
[ 52%] Built target smqt
[ 61%] Built target pebb
[ 70%] Built target gm
[ 79%] Built target gst
[ 89%] Built target pqt
[100%] Built target iet
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: rocm-validation-suite
CPack: - Install project: rocm-validation-suite
CPack: Create package
CPack: - package: /root/lucy_tools/build/rocm-validation-suite-0.0.15.deb generated.
CPack: Create package using RPM
CPack: Install projects
CPack: - Run preinstall target for: rocm-validation-suite
CPack: - Install project: rocm-validation-suite
CPack: Create package
CMake Error at /usr/share/cmake-3.5/Modules/CPackRPM.cmake:1069 (message):
  RPM package requires rpmbuild executable
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/CPackRPM.cmake:1787 (cpack_rpm_generate_package)

CPack Error: Error while execution CPackRPM.cmake
CPack Error: Cannot find rpmbuild
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: rocm-validation-suite
Makefile:116: recipe for target 'package' failed
make: *** [package] Error 1

**Comment by mlucinhdl** [comment]
You may ignore this error. RPM packages will not be generated on Ubuntu.
