### ISSUE TITLE
PQT regression goes to dead loop on one Vega20 GPU board

### ISSUE THREAD

**Issue by chaojunliu2015** [ROCm-Developer-Tools/ROCmValidationSuite#255]
root@gfxval-OG:~/lucy_tools/ROCmValidationSuite/regression# ./run_regression.py
pwd: ignoring non-option arguments
/root/lucy_tools/ROCmValidationSuite/regression
Total number of combinations (including invalid) is 32
Iteration is 0, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile0.conf
Iteration is 1, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile1.conf
Iteration is 2, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile2.conf
Iteration is 3, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile3.conf
Iteration is 4, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile4.conf
Iteration is 5, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile5.conf
Iteration is 6, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile6.conf
Iteration is 7, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile7.conf
Iteration is 8, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile8.conf
Iteration is 9, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile9.conf
Iteration is 10, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile10.conf
Iteration is 11, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile11.conf
Iteration is 12, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile12.conf
Iteration is 13, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile13.conf
Iteration is 14, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile14.conf
Iteration is 15, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile15.conf
Iteration is 16, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile16.conf
Iteration is 17, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile17.conf
Iteration is 18, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile18.conf
Iteration is 19, working on conf file /root/lucy_tools/ROCmValidationSuite/../build/regression/conf/demofile19.conf
demofile0.conf
Found file with name : demofile0.conf

[RESULT] [  1956.446440] [action_1] p2p 18984 18984 false
[INFO  ] [  1956.446451] [action_1] No GPU/peer combination matches criteria from test configuation
Found json file demofile

demofile0.conf
Found file with name : demofile0.conf

[RESULT] [  1956.505139] [action_1] p2p 18984 18984 false
[INFO  ] [  1956.505150] [action_1] No GPU/peer combination matches criteria from test configuation
Found json file demofile

demofile0.conf
Found file with name : demofile0.conf

[RESULT] [  1956.567096] [action_1] p2p 18984 18984 false
[INFO  ] [  1956.567107] [action_1] No GPU/peer combination matches criteria from test configuation
Found json file demofile

demofile0.conf
Found file with name : demofile0.conf

[RESULT] [  1956.635147] [action_1] p2p 18984 18984 false
[INFO  ] [  1956.635158] [action_1] No GPU/peer combination matches criteria from test configuation
Found json file demofile

demofile0.conf
Found file with name : demofile0.conf

[RESULT] [  1956.702659] [action_1] p2p 18984 18984 false
[INFO  ] [  1956.702670] [action_1] No GPU/peer combination matches criteria from test configuation
Found json file demofile

demofile0.conf
Found file with name : demofile0.conf

[RESULT] [  1956.769476] [action_1] p2p 18984 18984 false
[INFO  ] [  1956.769486] [action_1] No GPU/peer combination matches criteria from test configuation
Found json file demofile

demofile0.conf
Found file with name : demofile0.conf

[RESULT] [  1956.836929] [action_1] p2p 18984 18984 false
[INFO  ] [  1956.836940] [action_1] No GPU/peer combination matches criteria from test configuation
Found json file demofile

**Comment by dmatichdl** [comment]
Hi chaojunliu2015,

In order to check p2p bandwidth multiple GPUs are required.

Best regards
