### ISSUE TITLE
Some modules cannot run under installation dir /opt/rocm/rvs

### ISSUE THREAD

**Issue by chaojunliu2015** [ROCm-Developer-Tools/ROCmValidationSuite#266]
Some modules cannot run under installation dir /opt/rocm/rvs. Here are examples,

root@gfxval-OG:/opt/rocm/rvs# ./rvs -c ./conf/iet.conf
RVS-CLI: could not load .so '/opt/rocm/rvs//libiet.so.0' reason: librocblas.so.0: cannot open shared object file: No such file or directory
RVS-CLI: module 'iet' not available.
RVS-CLI: action 'action_1' could not crate action object in module 'iet'

root@gfxval-OG:/opt/rocm/rvs# ./rvs -c ./conf/gst.conf
RVS-CLI: could not load .so '/opt/rocm/rvs//libgst.so.0' reason: librocblas.so.0: cannot open shared object file: No such file or directory
RVS-CLI: module 'gst' not available.
RVS-CLI: action 'action_1' could not crate action object in module 'gst'

**Comment by jedwards-AMD** [comment]
Is rocblas installed?

**Comment by chaojunliu2015** [comment]
rocblas installed followed the instuctions.

**Comment by mlucinhdl** [comment]
Could you please execute and send us output from:
`./rvs --version`
`./rvs -t`

**Comment by chaojunliu2015** [comment]
root@gfxval-OG:/opt/rocm/rvs# ./rvs --version
0.0.17

root@gfxval-OG:/opt/rocm/rvs# ./rvs -t

ROCm Validation Suite (version 0.0.17)

Modules available:
        gm:
                Description: ROCm Validation Suite GM module
                config: monitor (bool)
                output: state (string)
        gpup:
                Description: ROCm Validation Suite GPUP module
                config: module (string), version (string), installed (bool),user (string), groups (collection of strings), file (string),                                owner (string), group (string), permission (int), type (int), exists (bool)
                output: pass (bool)
RVS-CLI: could not load .so '/opt/rocm/rvs//libgst.so.0' reason: librocblas.so.0: cannot open shared object file: No such file or directo                               ry
RVS-CLI: module 'gst' not available.
RVS-CLI: could not open module: gst
RVS-CLI: could not load .so '/opt/rocm/rvs//libiet.so.0' reason: librocblas.so.0: cannot open shared object file: No such file or directo                               ry
RVS-CLI: module 'iet' not available.
RVS-CLI: could not open module: iet
        pebb:
                Description: ROCm Validation Suite PEBB module
                config: host_to_device (bool), device_to_host (bool), log_interval (integer)
                output: interval_bandwidth (float array), bandwidth (float array)
        peqt:
                Description: ROCm Validation Suite PEQT module
                config: capability ({string, string})
                output: pass (bool)
        pesm:
                Description: ROCm Validation Suite PESM module
                config: monitor (bool)
                output: state (string)
        pqt:
                Description: ROCm Validation Suite PQT module
                config: peers (Collection of Strings), peer_deviceid (Integer), test_bandwidth (Bool), bidirectional(Bool), parallel (Boo                               l), duration (Integer), log_interval (Integer)
                output: p2p_result (Collection of Bools), peers (Collection of Strings), peer_deviceid (Integer), test_bandwidth (Bool),                                interval_bandwidth (Collection of Floats), bandwidth (Collection of Floats)
        rcqt:
                Description: ROCm Configuration Qualification Tool module
                config: package (string), version (string), installed (bool), user (string), groups (collection of strings), file (string                               ), owner (string), group (string), permission (int), type (int), exists (bool)
                output: pass (bool)
        smqt:
                Description: SBIOS Mapping Qualification Tool
                config: bar1_req_size(integer), bar1_base_addr_min(integer), bar1_base_addr_max(integer), bar2_req_size(integer), bar2_ba                               se_addr_min(integer), bar2_base_addr_max(integer), bar4_req_size(integer), bar4_base_addr_min(integer), bar4_base_addr_max(integer), bar5                               _req_size(integer)
                output: bar1_size(integer), bar1_base_addr(integer), bar2_size(integer), bar2_base_addr(integer), bar4_size(integer), bar                               4_base_addr(integer), bar5_size(integer), pass(bool)

**Comment by tchdldh** [comment]
Can you please run a _**ls /opt/rocm/rocblas**_ to check if the rocblas is there?
Please note that rocBLAS's _./install.sh -d_ does not install rocBLAS under the /opt/rocm. It only builds it under the _build_ folder.
To install rocBLAS under the /opt/rocm you can either run
**_./install.sh -i_** 
or 
**_sudo apt-get update
sudo apt-get install rocblas_**

**Comment by chaojunliu2015** [comment]
I installed rocBLAS, but it's disappeared(not found the reason yet). After I reinstalled rocBLAS, now rvs works under installation directory. Thank you.
You can close this issue now.

**Comment by kevin1985y** [comment]
> I installed rocBLAS, but it's disappeared(not found the reason yet). After I **_reinstalled_** rocBLAS, now rvs works under installation directory. Thank you. You can close this issue now.



Hi @chaojunliu2015 

It still displays 
module 'gstt' not available.
module 'iet' not available.
after I reinstalled rocBLAS.

Could you please share your steps that how you fix this issue?
Thanks.
