### ISSUE TITLE
Dual root intel machine pebb_test1.conf disagrees with  rocm_bandwidth_test

### ISSUE THREAD

**Issue by djygithub** [ROCm-Developer-Tools/ROCmValidationSuite#267]
https://www.supermicro.com/products/system/1u/1029/SYS-1029GQ-TRT.cfm
[rvs20180913.docx](https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/files/2380965/rvs20180913.docx)

rocm@rocmp2p:~/myrvs20180913/build/bin$ sudo ./rvs -c conf/pebb_test1.conf -d 3
RVS-PEBB: internal error, src: 0   dst: 2   current size: 1024 status -1
[INFO  ] [ 10888.778897] [action_1] pcie-bandwidth  [1/8] 0 49939  h2d: true  d2h: false  (pending)
RVS-PEBB: internal error, src: 1   dst: 2   current size: 1024 status -1
[INFO  ] [ 10888.780203] [action_1] pcie-bandwidth  [2/8] 1 49939  h2d: true  d2h: false  (pending)
RVS-PEBB: internal error, src: 0   dst: 3   current size: 1024 status -1
[INFO  ] [ 10888.781503] [action_1] pcie-bandwidth  [3/8] 0 9384  h2d: true  d2h: false  (pending)
RVS-PEBB: internal error, src: 1   dst: 3   current size: 1024 status -1
[INFO  ] [ 10888.782723] [action_1] pcie-bandwidth  [4/8] 1 9384  h2d: true  d2h: false  (pending)
RVS-PEBB: internal error, src: 0   dst: 4   current size: 1024 status -1
[INFO  ] [ 10888.783923] [action_1] pcie-bandwidth  [5/8] 0 32048  h2d: true  d2h: false  (pending)
RVS-PEBB: internal error, src: 1   dst: 4   current size: 1024 status -1
[INFO  ] [ 10888.785134] [action_1] pcie-bandwidth  [6/8] 1 32048  h2d: true  d2h: false  (pending)
RVS-PEBB: internal error, src: 0   dst: 5   current size: 1024 status -1
[INFO  ] [ 10888.786352] [action_1] pcie-bandwidth  [7/8] 0 5135  h2d: true  d2h: false  (pending)
RVS-PEBB: internal error, src: 1   dst: 5   current size: 1024 status -1
[INFO  ] [ 10888.787571] [action_1] pcie-bandwidth  [8/8] 1 5135  h2d: true  d2h: false  (pending)
[RESULT] [ 10888.788690] [action_1] pcie-bandwidth  [1/8] 0 49939  h2d: true  d2h: false  (not measured)  duration: 0.000000 sec
[RESULT] [ 10888.788725] [action_1] pcie-bandwidth  [2/8] 1 49939  h2d: true  d2h: false  (not measured)  duration: 0.000000 sec
[RESULT] [ 10888.788748] [action_1] pcie-bandwidth  [3/8] 0 9384  h2d: true  d2h: false  (not measured)  duration: 0.000000 sec
[RESULT] [ 10888.788768] [action_1] pcie-bandwidth  [4/8] 1 9384  h2d: true  d2h: false  (not measured)  duration: 0.000000 sec
[RESULT] [ 10888.788790] [action_1] pcie-bandwidth  [5/8] 0 32048  h2d: true  d2h: false  (not measured)  duration: 0.000000 sec
[RESULT] [ 10888.788813] [action_1] pcie-bandwidth  [6/8] 1 32048  h2d: true  d2h: false  (not measured)  duration: 0.000000 sec
[RESULT] [ 10888.788836] [action_1] pcie-bandwidth  [7/8] 0 5135  h2d: true  d2h: false  (not measured)  duration: 0.000000 sec
[RESULT] [ 10888.788859] [action_1] pcie-bandwidth  [8/8] 1 5135  h2d: true  d2h: false  (not measured)  duration: 0.000000 sec

`
rocm@rocmp2p:~/MI25_Test_Kit_v6$ ./rocm_bandwidth_test
........................................
................................

          RocmBandwidthTest Version: 1.0.0

          Device: 0,  Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
          Device: 1,  Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz
          Device: 2,  Device 6860
          Device: 3,  Device 6860
          Device: 4,  Device 6860
          Device: 5,  Device 6860

          Device Access

          D/D       0         1         2         3         4         5

          0         1         1         1         1         1         1

          1         1         1         1         1         1         1

          2         1         1         1         0         0         0

          3         1         1         0         1         0         0

          4         1         1         0         0         1         0

          5         1         1         0         0         0         1

          Device Numa Distance

          D/D       0         1         2         3         4         5

          0         0         21        N/A       N/A       N/A       N/A

          1         21        0         N/A       N/A       N/A       N/A

          2         20        41        0         N/A       N/A       N/A

          3         20        41        N/A       0         N/A       N/A

          4         41        20        N/A       N/A       0         N/A

          5         41        20        N/A       N/A       N/A       0

          Unidirectional peak bandwidth GB/s

          D/D       0           1           2           3           4           5

          0         N/A         N/A         13.857875   13.842693   13.823227   13.849041

          1         N/A         N/A         13.858722   13.841009   13.845618   13.849464

          2         14.322782   14.323237   385.837240  N/A         N/A         N/A

          3         14.322858   14.321950   N/A         385.346502  N/A         N/A

          4         14.319640   14.294790   N/A         N/A         386.990889  N/A

          5         14.319224   14.319228   N/A         N/A         N/A         383.064419

          Bdirectional peak bandwidth GB/s

          D/D       0           1           2           3           4           5

          0         N/A         N/A         23.140940   23.125701   22.815210   22.881539

          1         N/A         N/A         22.775017   23.134562   22.909831   22.793458

          2         23.106706   23.120860   N/A         N/A         N/A         N/A

          3         23.101520   23.112722   N/A         N/A         N/A         N/A

          4         23.299893   22.778499   N/A         N/A         N/A         N/A

          5         23.290969   23.299954   N/A         N/A         N/A         N/A

rocm@rocmp2p:~/MI25_Test_Kit_v6$
`

**Comment by mlucinhdl** [comment]
Fixes merged in #272
