### ISSUE TITLE
PEBB module ignores duration

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#286]
The PEBB module is ignoring the duration key, and will only perform a transfer test for as long as it takes for the transfer to finish. This makes the log_interval key useless and doesn't allow the user to determine the sustained data-transfer rates between host and device. Consider this configuration file:
actions:
- name: h2d-d2h
  device: all
  duration: 100000
  module: pebb
  log_interval: 1000
  device_to_host: true
  host_to_device: false
  block_size: 10240000
.
According to the RVS specification this should result in 100 INFO messages giving the average bandwidth over a 1 second window (the log_interval) for each device being measured. Instead, it only gives one RESULT line per device. The result is required output, but the time series of the test is never executed.

**Comment by mlucinhdl** [comment]
Please try running with -d 3 switch to allow INFO messages to be displayed.

**Comment by jedwards-AMD** [comment]
I have used the -d 3 option. Moreover I have attempted to run using variable durations. Do you have a config script that will run with longer duration than a single copy? Maybe this is an issue with parameter passing.

**Comment by mlucinhdl** [comment]
It seems you are missing `parallel: true`
When `parallel` is missing it is looking for `count` . If not found, the default is 1 and test exits quickly.

**Comment by mlucinhdl** [comment]
Just a small clarification: if `parallel:false` test will run until `duration` expires of number of **test transfers** reaches `count` (whichever comes first).
We may change interpretation of `count` so that it repeats test (as if there were multiple actions in .conf file)

As per duration I have to double check.

**Comment by mlucinhdl** [comment]
Considered approved.
