### ISSUE TITLE
PQT module ignores duration key

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#287]
The PQT module is ignoring the duration key, and will only perform a transfer test for as long as it takes for the transfer to finish. This makes the log_interval key useless and doesn't allow the user to determine the sustained data-transfer rates between host and device. Consider this configuration file:
actions:
- name: action_1
  device: all
  duration: 100000
  module: pqt
  log_interval: 1000
  peers: all
  test_bandwidth: true
  bidirectional: true
  block_size: 1000000 
  .
 According to the RVS specification this should result in 100 INFO messages giving the average bandwidth over a 1 second window (the log_interval) for each device being measured. Instead, it only gives one RESULT line per device. The result is required output, but the time series of the test is never executed.

**Comment by mlucinhdl** [comment]
Considered approved.
