### ISSUE TITLE
Add regex capability to rcqt strings.

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#288]
This is a feature request. Would it be possible to add regex capabilities to the rcqt strings that are being checked for correctness. For example, when a kernel check is made could we specify a kernel like this:
- name: ROCm kernel support check
  device: all
  module: rcqt
  os_version: Ubuntu 16.04.5 LTS
  kernel_version: 4.13.0*
.
and have it match this 4.13.0-32-generic.
.
I would want to extend this to all types strings in the rcqt checking tests.

**Comment by mlucinhdl** [comment]
Merged in #364
