### ISSUE TITLE
P2P-bandwidth No peers found...

### ISSUE THREAD

**Issue by kennethchiu-smc** [ROCm-Developer-Tools/ROCmValidationSuite#289]
We retested 2 x MI25 on Supermicro X11DGQ with new test tools.
It looks P2P still have some problems by using the RVS tool. Two GPU cannot peer to each other on dual root setup over UPI.
[RESULT] [    94.478367] [action_4] p2p 7707 7707 peers:false distance:-1
[RESULT] [    94.478397] [action_4] p2p 7707 51576 peers:false distance:-1
[RESULT] [    94.478415] [action_4] p2p 51576 7707 peers:false distance:-1
[RESULT] [    94.478424] [action_4] p2p 51576 51576 peers:false distance:-1
[ERROR ] [    94.478431] [action_4] p2p-bandwidth No peers found
 
If I put 2GPU under the same CPU, it looks okay. So the P2P over the UPI maybe still have problem.
[RESULT] [  1231.828304] [action_2] peqt TRUE
[RESULT] [  1231.981221] [action_3] pcie-bandwidth 0 2 7707  distance:20 PCIe:20
[RESULT] [  1231.981311] [action_3] pcie-bandwidth 1 2 7707  distance:41 QPI:41
[RESULT] [  1231.981373] [action_3] pcie-bandwidth 0 3 63982  distance:20 PCIe:20
[RESULT] [  1231.981427] [action_3] pcie-bandwidth 1 3 63982  distance:41 QPI:41
[INFO  ] [  1232.2409  ] [action_3] pcie-bandwidth  [1/4] 0 7707  h2d: true  d2h: false  12.562 GBps
[INFO  ] [  1232.9325  ] [action_3] pcie-bandwidth  [2/4] 1 7707  h2d: true  d2h: false  12.567 GBps
[INFO  ] [  1232.26636 ] [action_3] pcie-bandwidth  [3/4] 0 63982  h2d: true  d2h: false  12.571 GBps
[INFO  ] [  1232.32599 ] [action_3] pcie-bandwidth  [4/4] 1 63982  h2d: true  d2h: false  12.477 GBps
[RESULT] [  1232.33685 ] [action_3] pcie-bandwidth  [1/4] 0 7707  h2d: true  d2h: false  12.562 GBps  duration: 0.000759 sec
[RESULT] [  1232.33698 ] [action_3] pcie-bandwidth  [2/4] 1 7707  h2d: true  d2h: false  12.567 GBps  duration: 0.000759 sec
[RESULT] [  1232.33706 ] [action_3] pcie-bandwidth  [3/4] 0 63982  h2d: true  d2h: false  12.571 GBps  duration: 0.000759 sec
[RESULT] [  1232.33714 ] [action_3] pcie-bandwidth  [4/4] 1 63982  h2d: true  d2h: false  12.477 GBps  duration: 0.000764 sec
[RESULT] [  1232.35258 ] [action_4] p2p 7707 7707 peers:false distance:-1
[RESULT] [  1232.35294 ] [action_4] p2p 7707 63982 peers:true distance:40 PCIe:40
[RESULT] [  1232.35322 ] [action_4] p2p 63982 7707 peers:true distance:40 PCIe:40
[RESULT] [  1232.35346 ] [action_4] p2p 63982 63982 peers:false distance:-1
[INFO  ] [  1232.43996 ] [action_4] p2p-bandwidth  [1/2] 7707 63982  bidirectional: true  15.886 GBps
[INFO  ] [  1232.52321 ] [action_4] p2p-bandwidth  [2/2] 63982 7707  bidirectional: true  17.108 GBps
[RESULT] [  1232.53436 ] [action_4] p2p-bandwidth  [1/2] 7707 63982  bidirectional: true  15.886 GBps  duration: 0.001524 sec
[RESULT] [  1232.54530 ] [action_4] p2p-bandwidth  [2/2] 63982 7707  bidirectional: true  17.108 GBps  duration: 0.001415 sec

[difCPU.txt](https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/files/2517066/difCPU.txt)
[sameCPU.txt](https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/files/2517067/sameCPU.txt)

**Comment by kennethchiu-smc** [comment]
1.	The RVS version is 0.0.21
2.	Here is the bandwidth_test result in RVS:
lab@lab:~/RVS/build/bin$ sudo ./rvs -c conf/pebb_test1.conf -d 3
[RESULT] [   271.84031 ] [action_1] pcie-bandwidth 0 2 7707  distance:20 PCIe:20
[RESULT] [   271.84120 ] [action_1] pcie-bandwidth 1 2 7707  distance:41 QPI:41
[RESULT] [   271.84183 ] [action_1] pcie-bandwidth 0 3 63982  distance:20 PCIe:20
[RESULT] [   271.84239 ] [action_1] pcie-bandwidth 1 3 63982  distance:41 QPI:41
[RESULT] [   271.84295 ] [action_1] pcie-bandwidth 0 4 41051  distance:41 QPI:41
[RESULT] [   271.84348 ] [action_1] pcie-bandwidth 1 4 41051  distance:20 PCIe:20
[RESULT] [   271.84403 ] [action_1] pcie-bandwidth 0 5 51576  distance:41 QPI:41
[RESULT] [   271.84453 ] [action_1] pcie-bandwidth 1 5 51576  distance:20 PCIe:20
[INFO  ] [   271.106563] [action_1] pcie-bandwidth  [1/8] 0 7707  h2d: true  d2h: false  12.841 GBps
[INFO  ] [   271.112995] [action_1] pcie-bandwidth  [2/8] 1 7707  h2d: true  d2h: false  12.572 GBps
[INFO  ] [   271.133592] [action_1] pcie-bandwidth  [3/8] 0 63982  h2d: true  d2h: false  12.838 GBps
[INFO  ] [   271.140650] [action_1] pcie-bandwidth  [4/8] 1 63982  h2d: true  d2h: false  12.840 GBps
[INFO  ] [   271.160665] [action_1] pcie-bandwidth  [5/8] 0 41051  h2d: true  d2h: false  12.835 GBps
[INFO  ] [   271.168225] [action_1] pcie-bandwidth  [6/8] 1 41051  h2d: true  d2h: false  10.137 GBps
[INFO  ] [   271.188514] [action_1] pcie-bandwidth  [7/8] 0 51576  h2d: true  d2h: false  12.830 GBps
[INFO  ] [   271.194793] [action_1] pcie-bandwidth  [8/8] 1 51576  h2d: true  d2h: false  11.309 GBps
[RESULT] [   271.195933] [action_1] pcie-bandwidth  [1/8] 0 7707  h2d: true  d2h: false  12.841 GBps  duration: 0.000743 sec
[RESULT] [   271.195956] [action_1] pcie-bandwidth  [2/8] 1 7707  h2d: true  d2h: false  12.572 GBps  duration: 0.000759 sec
[RESULT] [   271.195965] [action_1] pcie-bandwidth  [3/8] 0 63982  h2d: true  d2h: false  12.838 GBps  duration: 0.000743 sec
[RESULT] [   271.195973] [action_1] pcie-bandwidth  [4/8] 1 63982  h2d: true  d2h: false  12.840 GBps  duration: 0.000743 sec
[RESULT] [   271.195981] [action_1] pcie-bandwidth  [5/8] 0 41051  h2d: true  d2h: false  12.835 GBps  duration: 0.000743 sec
[RESULT] [   271.195989] [action_1] pcie-bandwidth  [6/8] 1 41051  h2d: true  d2h: false  10.137 GBps  duration: 0.000941 sec
[RESULT] [   271.195996] [action_1] pcie-bandwidth  [7/8] 0 51576  h2d: true  d2h: false  12.830 GBps  duration: 0.000743 sec
[RESULT] [   271.196017] [action_1] pcie-bandwidth  [8/8] 1 51576  h2d: true  d2h: false  11.309 GBps  duration: 0.000843 sec

During the bandwidth test, we didn't see any bandwidth test thru UPI as well. Maybe is that the issue?

**Comment by mlucinhdl** [comment]
@kennethchiu-smc 
1. PEBB test: Admittedly, "pcie-bandwidth" label is a bit misleading. In fact, PEBB test measures bandwidth for all available HSA nodes regardless of link type. If you want to filter out on specific link type, please wait for version 0.22
Consequently, from what I can see in the output, QPI links are also tested (see transfers [2/8], [4/8], [5/8], [7/8])

2. PQT test ("p2p"): it seems that GPUs in your syst are in fact not peers in HSA sence. As suggested, please run `rocm_bandwidth_test` and look into connection matrix to verify this.

**Comment by mlucinhdl** [comment]
Well, this confirms that GPUs on this system are not peers, hence no p2p bandwidth test is performed.
As per newer tool, there is nothing that I am aware of (except for RVS of course) but you may contact Adrian (@jedwards-AMD)

**Comment by jedwards-AMD** [comment]
Support for p2p occurs at the driver/hardware level, and has nothing to do with a "tool". The topology of the interconnections between GPUs is what determines if GPUs are peers.
