### ISSUE TITLE
CMAKE_BUILD_TYPE is always defined as empty string.

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#295]
On line 36 of the CMakeLists.txt file the following is checked:
if (DEFINED CMAKE_BUILD_TYPE)

However, the CMAKE_BUILD_TYPE is always defined, and will default to the empty string. This will cause a cmake error on line 37 if CMAKE_BUILD_TYPE isn't set to a string value:

-- CMAKE_BINARY_DIR = /home/user1/git/build
-- CMAKE_CURRENT_SOURCE_DIR = /home/user1/git/ROCmValidationSuite
-- CMAKE_BUILD_TYPE = 
CMake Error at CMakeLists.txt:36 (if):
  if given arguments:
    "STREQUAL" "Debug"
  Unknown arguments specified
-- Configuring incomplete, errors occurred!
See also "/home/user1/git/build/CMakeFiles/CMakeOutput.log".
See also "/home/user1/git/build/CMakeFiles/CMakeError.log".
.
The check should be changed to:

if (CMAKE_BUILD_TYPE) - Which will be false if the variable is the empty string.

**Comment by mlucinhdl** [comment]
Fix merged in #298. See comment for #296
