### ISSUE TITLE
PEQT module prints out results in ALL-CAPS

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#300]
This is the output of modules performing checks:
[RESULT] [2067425.555617] [Check PCIe link capabilities] peqt FALSE
[RESULT] [2067425.572990] [Check rock-dkms package] rcqt packagecheck rock-dkms true
[RESULT] [2067425.592214] [Check hsakmt-roct package] rcqt packagecheck hsakmt-roct true
Notice that the peqt module prints results in all-caps while the rcqt module doesn't. All modules should print these strings consistently. I prefer lower case.

**Comment by jedwards-AMD** [comment]
Also, would it be possible to print out the BUS ID of the PCIe link in the INFO and RESULT lines?

**Comment by mlucinhdl** [comment]
@jedwards-AMD: can you please pull the latest master and review the output using:
```
 sudo ./rvs -c conf/peqt18.conf -d 3
```
Basically, we display bud_id as one capability. We are not sure if this is what you had in mind? 
Also, we suggest printing <gpu_id> (and not bus_id) along with INFO and RESULT messages as GPU ID is used in RVS in general.

Please let us know how to proceed.

**Comment by mlucinhdl** [comment]
Considered approved.
