### ISSUE TITLE
The pqt module doesn't exit after displaying p2p info.

### ISSUE THREAD

**Issue by jedwards-AMD** [ROCm-Developer-Tools/ROCmValidationSuite#301]
The P2P information on a system can be displayed using the following config file:
actions:
# Display P2P Info
- name: Display P2P Info
  device: all
  module: pqt
  peers: all
  test_bandwidth: false
  bidirectional: false
  parallel: false
.
If rvs is run using this configuration file the information is printed and the process doesn't exit. This is the backtrace where the code is hanging:

Thread 1 "rvs" received signal SIGINT, Interrupt.
0x00007ffff6b36b27 in pqtaction::run_single() () from /home/user1/git/build/bin//libpqt.so.0
(gdb) bt
#0  0x00007ffff6b36b27 in pqtaction::run_single() () from /home/user1/git/build/bin//libpqt.so.0
#1  0x00007ffff6b367ea in pqtaction::run() () from /home/user1/git/build/bin//libpqt.so.0
#2  0x00007ffff6b2d931 in rvs_module_action_run () from /home/user1/git/build/bin//libpqt.so.0
#3  0x000000000040e05b in rvs::if1::run() ()
#4  0x000000000041bf9e in rvs::exec::do_yaml(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#5  0x000000000041ad40 in rvs::exec::run() ()
#6  0x0000000000405fab in main ()

It appears the run isn't being terminated correctly, and the thread won't exit.

**Comment by mlucinhdl** [comment]
@jedwards-AMD : Please pull master and retest.

**Comment by mlucinhdl** [comment]
Fixed through #303
