### ISSUE TITLE
/opt/rocm/lib64 not included in build library path

### ISSUE THREAD

**Issue by jcasu-penguin** [ROCm-Developer-Tools/ROCmValidationSuite#311]
Manifests as an issue building the pebb plugin:

[ 70%] Linking CXX shared library ../bin/libpebb.so.0.0.0
/usr/bin/ld: cannot find -lhsakmt
collect2: error: ld returned 1 exit status

workaround by manually adding symbolic links to libhsakmt under /opt/rocm/lib.

**Comment by mlucinhdl** [comment]
Fix merged in #337
