### ISSUE TITLE
module 'gst' not available after roc master upgraded to roc_master_10133

### ISSUE THREAD

**Issue by chaojunliu2015** [ROCm-Developer-Tools/ROCmValidationSuite#426]
Upgrade roc master release to the most recent best known version roc_master_10133.
Build and run RVS, got the following errors. Other modules seem working fine.

root@IVT9Lucy:~/RVS/build/bin/conf# ~/RVS/build/bin/rvs -c gst_1.conf
RVS-ERROR [CLI] could not load .so '/root/RVS/build/bin//libgst.so'
RVS-ERROR [CLI] reason: '/opt/rocm/lib/librocblas.so.0: undefined symbol: _ZN8hip_impl22hipLaunchKernelGGLImplEmRK4dim3S2_jP12ihipStream_tPPv'
RVS-ERROR [CLI] module 'gst' not available.
RVS-ERROR [CLI] action 'action_1' could not crate action object in module 'gst'

**Comment by djygithub** [comment]
Try building a local copy of rocblas, adjust your cmake as follows:
``` mkdir myrvs20190701
 cd myrvs20190701/
 git clone https://github.com/ROCm-Developer-Tools/ROCmValidationSuite.git
 cd ROCmValidationSuite/
 cmake  -DRVS_ROCBLAS=1 ./ -B../build
 make -C ../build
 cd ..
 cd build/
 cd bin
 sudo ./rvs -d 3
