### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by gggh000** [ROCm-Developer-Tools/ROCmValidationSuite#428]
make -C ../build
resulted in:

root@MS-7B22:/git.co/rocm-devtools/ROCmValidationSuite# make -C ../build
make: Entering directory '/git.co/rocm-devtools/build'
make[1]: Entering directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
Scanning dependencies of target rvs_bintest_folder
make[2]: Leaving directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
[  1%] Create the bintest directory
make[2]: Leaving directory '/git.co/rocm-devtools/build'
[  1%] Built target rvs_bintest_folder
make[2]: Entering directory '/git.co/rocm-devtools/build'
Scanning dependencies of target rvs_bin_folder
make[2]: Leaving directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
[  2%] Create the bin directory
make[2]: Leaving directory '/git.co/rocm-devtools/build'
[  2%] Built target rvs_bin_folder
make[2]: Entering directory '/git.co/rocm-devtools/build'
Scanning dependencies of target rvs_doc
make[2]: Leaving directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
[  2%] Create the doc directory
make[2]: Leaving directory '/git.co/rocm-devtools/build'
[  2%] Built target rvs_doc
make[2]: Entering directory '/git.co/rocm-devtools/build'
Scanning dependencies of target rvslibrt
make[2]: Leaving directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
[  3%] Building CXX object rvslib/CMakeFiles/rvslibrt.dir/__/src/rvsloglp.cpp.o
[  3%] Building CXX object rvslib/CMakeFiles/rvslibrt.dir/__/src/pci_caps.cpp.o
/git.co/rocm-devtools/ROCmValidationSuite/src/pci_caps.cpp:32:10: fatal error: pci/pci.h: No such file or directory
 #include <pci/pci.h>
          ^~~~~~~~~~~
compilation terminated.
rvslib/CMakeFiles/rvslibrt.dir/build.make:86: recipe for target 'rvslib/CMakeFiles/rvslibrt.dir/__/src/pci_caps.cpp.o' failed
make[2]: *** [rvslib/CMakeFiles/rvslibrt.dir/__/src/pci_caps.cpp.o] Error 1
make[2]: Leaving directory '/git.co/rocm-devtools/build'
CMakeFiles/Makefile2:882: recipe for target 'rvslib/CMakeFiles/rvslibrt.dir/all' failed
make[1]: *** [rvslib/CMakeFiles/rvslibrt.dir/all] Error 2
make[1]: Leaving directory '/git.co/rocm-devtools/build'
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/git.co/rocm-devtools/build'
root@guyen-MS-7B22:/git.co/rocm-devtools/ROCmValidationSuite# git remote -v
origin	https://github.com/ROCm-Developer-Tools/ROCmValidationSuite (fetch)
origin	https://github.com/ROCm-Developer-Tools/ROCmValidationSuite (push)
root@MS-7B22:/git.co/rocm-devtools/ROCmValidationSuite# git branch
* master
root@MS-7B22:/git.co/rocm-devtools/ROCmValidationSuite# 
root@guyen-MS-7B22:/git.co/rocm-devtools/ROCmValidationSuite# make -C ../build
make: Entering directory '/git.co/rocm-devtools/build'
make[1]: Entering directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
Scanning dependencies of target rvs_bintest_folder
make[2]: Leaving directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
[  1%] Create the bintest directory
make[2]: Leaving directory '/git.co/rocm-devtools/build'
[  1%] Built target rvs_bintest_folder
make[2]: Entering directory '/git.co/rocm-devtools/build'
Scanning dependencies of target rvs_bin_folder
make[2]: Leaving directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
[  2%] Create the bin directory
make[2]: Leaving directory '/git.co/rocm-devtools/build'
[  2%] Built target rvs_bin_folder
make[2]: Entering directory '/git.co/rocm-devtools/build'
Scanning dependencies of target rvs_doc
make[2]: Leaving directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
[  2%] Create the doc directory
make[2]: Leaving directory '/git.co/rocm-devtools/build'
[  2%] Built target rvs_doc
make[2]: Entering directory '/git.co/rocm-devtools/build'
Scanning dependencies of target rvslibrt
make[2]: Leaving directory '/git.co/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm-devtools/build'
[  3%] Building CXX object rvslib/CMakeFiles/rvslibrt.dir/__/src/rvsloglp.cpp.o
[  3%] Building CXX object rvslib/CMakeFiles/rvslibrt.dir/__/src/pci_caps.cpp.o
/git.co/rocm-devtools/ROCmValidationSuite/src/pci_caps.cpp:32:10: fatal error: pci/pci.h: No such file or directory
 #include <pci/pci.h>
          ^~~~~~~~~~~
compilation terminated.
rvslib/CMakeFiles/rvslibrt.dir/build.make:86: recipe for target 'rvslib/CMakeFiles/rvslibrt.dir/__/src/pci_caps.cpp.o' failed
make[2]: *** [rvslib/CMakeFiles/rvslibrt.dir/__/src/pci_caps.cpp.o] Error 1
make[2]: Leaving directory '/git.co/rocm-devtools/build'
CMakeFiles/Makefile2:882: recipe for target 'rvslib/CMakeFiles/rvslibrt.dir/all' failed
make[1]: *** [rvslib/CMakeFiles/rvslibrt.dir/all] Error 2
make[1]: Leaving directory '/git.co/rocm-devtools/build'
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/git.co/rocm-devtools/build'
root@MS-7B22:/git.co/rocm-devtools/ROCmValidationSuite# git remote -v
origin	https://github.com/ROCm-Developer-Tools/ROCmValidationSuite (fetch)
origin	https://github.com/ROCm-Developer-Tools/ROCmValidationSuite (push)
root@MS-7B22:/git.co/rocm-devtools/ROCmValidationSuite# git branch
* master
root@MS-7B22:/git.co/rocm-devtools/ROCmValidationSuite#

**Comment by djygithub** [comment]
Looks like https://github.com/RadeonOpenCompute/ROCT-Thunk-Interface/issues/7 did you install the prereq's? https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/blob/master/PREREQUISITES.md looks like libpci-dev is missing.

**Comment by ggghamd** [comment]
I noticed few prereqs needs to be satisfied and now I am getting following build error from either master or develop branch:
cmake version 3.7.2
gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
doxygen-latex/oldstable 1.8.13-4 all
libpci-dev/oldstable,now 1:3.5.2-1 amd64 [installed]

make -C ../build


make[2]: Leaving directory '/git.co/rocm/rocm-devtools/build'
make[2]: Entering directory '/git.co/rocm/rocm-devtools/build'
[ 59%] Building CXX object iet.so/CMakeFiles/iet.dir/src/iet_worker.cpp.o
/git.co/rocm/rocm-devtools/ROCmValidationSuite/iet.so/src/iet_worker.cpp: In member function ‘void IETWorker::compute_new_sgemm_freq(float)’:
/git.co/rocm/rocm-devtools/ROCmValidationSuite/iet.so/src/iet_worker.cpp:246:44: error: call of overloaded ‘abs(float&)’ is ambiguous
 float sgemm_delay_dev = (abs(diff_power) * sgemm_si_delay) / target_power;
 ^
In file included from /usr/include/c++/6/cstdlib:75:0,
 from /usr/include/c++/6/ext/string_conversions.h:41,
 from /usr/include/c++/6/bits/basic_string.h:5417,
 from /usr/include/c++/6/string:52,
 from /git.co/rocm/rocm-devtools/ROCmValidationSuite/iet.so/./include/iet_worker.h:28,
 from /git.co/rocm/rocm-devtools/ROCmValidationSuite/iet.so/src/iet_worker.cpp:25:
/usr/include/stdlib.h:735:12: note: candidate: int abs(int)
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
 ^~~
In file included from /usr/include/c++/6/ext/string_conversions.h:41:0,
 from /usr/include/c++/6/bits/basic_string.h:5417,
 from /usr/include/c++/6/string:52,
 from /git.co/rocm/rocm-devtools/ROCmValidationSuite/iet.so/./include/iet_worker.h:28,
 from /git.co/rocm/rocm-devtools/ROCmValidationSuite/iet.so/src/iet_worker.cpp:25:
/usr/include/c++/6/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
 abs(long long __x) { return __builtin_llabs (__x); }
 ^~~
/usr/include/c++/6/cstdlib:172:3: note: candidate: long int std::abs(long int)
 abs(long __i) { return __builtin_labs(__i); }
 ^~~
iet.so/CMakeFiles/iet.dir/build.make:110: recipe for target 'iet.so/CMakeFiles/iet.dir/src/iet_worker.cpp.o' failed
make[2]: *** [iet.so/CMakeFiles/iet.dir/src/iet_worker.cpp.o] Error 1
make[2]: Leaving directory '/git.co/rocm/rocm-devtools/build'
CMakeFiles/Makefile2:1226: recipe for target 'iet.so/CMakeFiles/iet.dir/all' failed
make[1]: *** [iet.so/CMakeFiles/iet.dir/all] Error 2
make[1]: Leaving directory '/git.co/rocm/rocm-devtools/build'
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/git.co/rocm/rocm-devtools/build'
root@debian-drop-2019-q3-rc6-gpu7-vf00-clone:/git.co/rocm/rocm-devtools/ROCmValidationSuite# pwd
/git.co/rocm/rocm-devtools/ROCmValidationSuite
root@debian-drop-2019-q3-rc6-gpu7-vf00-clone:/git.co/rocm/rocm-devtools/ROCmValidationSuite#
