### ISSUE TITLE
Cannot make a RVS package

### ISSUE THREAD

**Issue by chaojunliu2015** [ROCm-Developer-Tools/ROCmValidationSuite#437]
~/rvs/ROCmValidationSuite/build# make package
[ 88%] Built target unit.smqt.1
[ 90%] Built target smqt
[ 91%] Built target testif_fail_create_action
[ 92%] Built target testif_no_if_methods
[ 94%] Built target testif_no_if1_methods
[ 95%] Built target testif_no_if0
[ 97%] Built target testif_no_if0_methods
[ 99%] Built target testif_fail_init
[100%] Built target testif_no_if1
Run CPack packaging tool...
CPack: Create package using DEB
CPack: Install projects
CPack: - Run preinstall target for: rocm-validation-suite
CPack: - Install project: rocm-validation-suite
CMake Error at /root/rvs/ROCmValidationSuite/build/iet.so/cmake_install.cmake:77 (file):
  file INSTALL cannot find
  "/root/rvs/ROCmValidationSuite/build/bin/libiet.so.0".
Call Stack (most recent call first):
  /root/rvs/ROCmValidationSuite/build/cmake_install.cmake:71 (include)

CPack Error: Error when generating package: rocm-validation-suite
Makefile:118: recipe for target 'package' failed
make: *** [package] Error 1

**Comment by rakeshsv** [comment]
please try it now
