### ISSUE TITLE
hardcoded /opt/rocm/ paths

### ISSUE THREAD

**Issue by nolta** [ROCm-Developer-Tools/ROCmValidationSuite#481]
I'm trying to compile this using a [multi-version installation of ROCm](https://rocmdocs.amd.com/en/latest/Installation_Guide/Multiversion-Installation.html), but there are several places where `/opt/rocm/` is hardcoded.

For example, this line: https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/blob/7984af17ecd6ba5cae968ce9749aefb6d3acf184/babel.so/CMakeLists.txt#L115

I believe this line should be deleted, but at the very least `/opt/rocm` should be replaced with `${ROCM_PATH}`.

**Comment by nolta** [comment]
Yes, it's fixed on `master`.

**Comment by manoj-freyr** [comment]
Closing the issue, as master is the TOT for ROCmValidationSuite
