### ISSUE TITLE
hipErrorNoBinaryForGpu: Unable to find code object for all current devices!

### ISSUE THREAD

**Issue by honychiang2021** [ROCm-Developer-Tools/ROCmValidationSuite#556]
Hi Sir,

We run rvs 0.0.50203 in CentOS 8.5 to stress **AMD GPU Radeon™ PRO V520**, but get one error message below.
"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"
https://www.amd.com/zh-hant/products/server-accelerators/amd-radeon-pro-v520

Q1: Does RVS support to stress this GPU model?
Q2: How can we fix this error?

If we export "HSA_OVERRIDE_GFX_VERSION=10.3.0" Linux variable before starting rvs, gst module in rsv can run without error.
Q3: What is the purpose of this variable?

If we run rvs with gst_stress_3_hrs.conf on GPU Radeon™ PRO V520, but rsv can't exit or terminate automatically even though 3 hours is gone.  
https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/blob/master/rvs/conf/gst_stress_3_hrs.conf
Q4: How can we fix this problem?

Thanks,
Hony

**Comment by jkottiku** [comment]
I really doubt if AMD GPU Radeon™ PRO V520 supported by ROCm.
Please refer this [link](https://community.amd.com/t5/knowledge-base/amd-rocm-hardware-and-software-support-document/ta-p/489937).

**Comment by manoj-freyr** [comment]
Closing the issue as ROCm doesnt support the said card. And the flag is bypassing the runtime to say we are running on a supported hardware, which doesnt guarantee the code will work as expected. This could be the reason why stress test is stalling. 
We recommend you run RVS on platforms that ROCm supports. If on those RVS is not working, you can open an issue.
