### ISSUE TITLE
README link to examples broken

### ISSUE THREAD

**Issue by BalmaBrian** [ROCm-Developer-Tools/ROCmValidationSuite#595]
In the most recent updates, the link found in the screenshot below leads to a 404.
![image](https://user-images.githubusercontent.com/44687168/233509784-9d4b75b4-5283-40e4-bd3b-3021ffa79140.png)
The following should be linked -> https://github.com/ROCm-Developer-Tools/ROCmValidationSuite/blob/master/docs/ug1main.md

**Comment by manoj-freyr** [comment]
A reorg docs needed update in the link, the fix is master.
